name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Erlaubt das Schreiben von Inhalten in den main-Branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true
   
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.1'
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Hugo Dependencies
        run: hugo mod get

      - name: Build Hugo
        run: hugo

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # GitHub Actions Token für Authentifizierung
          publish_dir: ./public  # Verzeichnis, das du nach GitHub Pages pushen willst
